# Generated by Django 2.2.5 on 2021-06-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('fromPlace', models.CharField(max_length=200)),
                ('toPlace', models.CharField(max_length=200)),
                ('arrivalTime', models.CharField(max_length=200)),
                ('departureTime', models.CharField(max_length=200)),
                ('price', models.FloatField(null=True)),
            ],
        ),
    ]
