# Generated by Django 2.2.5 on 2021-06-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busbook', '0007_auto_20210628_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='currentSeat',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='seatNumber',
            field=models.IntegerField(null=True),
        ),
    ]
