# Generated by Django 2.2.5 on 2021-06-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busbook', '0008_auto_20210628_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='passengerAddress',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seatNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
